### ISSUE TITLE
[Feature 8] Emoji Manager

### ISSUE THREAD

**Issue by binwcs** [CSC207-2022F-UofT/course-project-SOLID-chat#11]

**Comment by binwcs** [comment]
<img width="864" alt="截屏2022-10-31 上午12 36 34" src="https://user-images.githubusercontent.com/67267301/198932540-49e51d06-bee4-4cdc-930a-1e3c17acb144.png">

**Comment by binwcs** [comment]
Develope the Emoji_Present and Emoji_Library Before 10th.Nov.     :>

**Comment by sogolsahebi** [comment]
My pull request reviewers would be Amy, James and Parmis.
